### ISSUE TITLE
Fails to generate report with same class on different build variants

### ISSUE THREAD

**Issue by GMCristiano** [Kotlin/kotlinx-kover#145]
When using different class implementation for different build variants on Android Studio, the final step to generate the xml/html result doesn't work. but If the same class implementation has similar line coverage or the class is excluded, everything works fine.

> Task :koverMergedXmlReport FAILED
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 215 out of bounds for length 193
        at com.intellij.rt.coverage.report.XMLCoverageReport.writeMethod(XMLCoverageReport.java:202)
        at com.intellij.rt.coverage.report.XMLCoverageReport.writeClass(XMLCoverageReport.java:178)
        at com.intellij.rt.coverage.report.XMLCoverageReport.writePackage(XMLCoverageReport.java:111)
        at com.intellij.rt.coverage.report.XMLCoverageReport.writeProject(XMLCoverageReport.java:93)
        at com.intellij.rt.coverage.report.XMLCoverageReport.write(XMLCoverageReport.java:58)
        at com.intellij.rt.coverage.report.Reporter.createXMLReport(Reporter.java:41)
        at com.intellij.rt.coverage.report.Main.main(Main.java:37)

**Comment by shanshin** [comment]
Relates #18

**Comment by shanshin** [comment]
Duplicates #78
