### ISSUE TITLE
RoboElectric based test failing with error java.lang.NoSuchMethodException: com.intellij.rt.coverage.data.ProjectData.traceLine

### ISSUE THREAD

**Issue by sreejith-hme** [Kotlin/kotlinx-kover#170]
Android project with Roboelectric Test Runner and Kotlin class/object, while running the test with code coverage, getting following error:

> 
> Plugin used : `org.jetbrains.kotlinx:kover:0.5.0`
> Roboelectric version: `4.7.3`
> Min Sdk Version = `21`
> Target Sdk Version = `30`
> Compile Sdk Version = `31`
> Build Tools Version = `30.0.3`
> Gradle Plugin Version = `0.21.0`
> Gradle Version = `7.1.3`
> Kotlin Version = `1.6.10`

> Android Studio Bumblebee | 2021.1.1 Patch 3
> Build #AI-211.7628.21.2111.8309675, built on March 16, 2022
> Runtime version: 11.0.11+0-b60-7772763 aarch64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> macOS 12.2.1
> Non-Bundled Plugins: org.jetbrains.kotlin (211-1.6.20-release-275-AS7442.40), 

`(Coverage): Error tracing class org.robolectric.Shadows
java.lang.NoSuchMethodException: com.intellij.rt.coverage.data.ProjectData.traceLine(java.lang.Object, int)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2475)
	at com.intellij.rt.coverage.data.ProjectData$MethodCaller.findMethod(ProjectData.java:365)
	at com.intellij.rt.coverage.data.ProjectData$MethodCaller.invoke(ProjectData.java:359)
	at com.intellij.rt.coverage.data.ProjectData.trace(ProjectData.java:277)
	at org.robolectric.Shadows.<clinit>(Shadows.java:699)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.robolectric.internal.bytecode.ShadowProviders.inClassLoader(ShadowProviders.java:64)
	at org.robolectric.internal.AndroidSandbox.<init>(AndroidSandbox.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.robolectric.util.inject.Injector.inject(Injector.java:250)
	at org.robolectric.util.inject.Injector.lambda$memoized$1(Injector.java:232)
	at org.robolectric.util.inject.Injector$MemoizingProvider.get(Injector.java:498)
	at org.robolectric.util.inject.Injector.getInstanceInternal(Injector.java:224)
	at org.robolectric.util.inject.Injector.getInstance(Injector.java:208)
	at org.robolectric.util.inject.Injector.access$700(Injector.java:96)
	at org.robolectric.util.inject.Injector$ScopeBuilderProvider.create(Injector.java:564)
	at org.robolectric.util.inject.Injector$ScopeBuilderProvider.lambda$get$0(Injector.java:547)
	at com.sun.proxy.$Proxy23.build(Unknown Source)
	at org.robolectric.internal.SandboxManager.getAndroidSandbox(SandboxManager.java:57)
	at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:285)
	at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:68)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:236)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:93)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)`
	
Any one knows how to resolve this ??

**Comment by shanshin** [comment]
Hi, sorry for the delayed answer.

Is the issue still reproducing? If yes, could you clarify at which test run this error is thrown, when starting from the IDE or when starting Gradle from the console?

**Comment by shanshin** [comment]
Feel free to open new bug issue if the problem reproduced again.
