### ISSUE TITLE
Failed to calculate the value of extension 'kover' property 'intellijEngineVersion'.

### ISSUE THREAD

**Issue by NikolayMetchev** [Kotlin/kotlinx-kover#199]
Recently we have started getting the exception outlined below in CI. It appears to be intermittent because subsequent runs succeed.

We have the following:
Kover 0.5.1
Gradle 7.5
Java 17.0.4
Kotlin 1.6.21
intellijEngineVersion 1.0.673

We have a multi-module project. 

```
[2022-08-03T13:54:12.889Z] * Exception is:

[2022-08-03T13:54:12.889Z] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':utils:common:test'.

[2022-08-03T13:54:12.889Z] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)

[2022-08-03T13:54:12.889Z] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)

[2022-08-03T13:54:12.889Z] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)

[2022-08-03T13:54:12.889Z] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)

[2022-08-03T13:54:12.889Z] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)

[2022-08-03T13:54:12.889Z] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)

[2022-08-03T13:54:12.889Z] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)

[2022-08-03T13:54:12.889Z] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)

[2022-08-03T13:54:12.889Z] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)

[2022-08-03T13:54:12.889Z] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)

[2022-08-03T13:54:12.889Z] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)

[2022-08-03T13:54:12.889Z] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)

[2022-08-03T13:54:12.889Z] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)

[2022-08-03T13:54:12.889Z] 	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:69)

[2022-08-03T13:54:12.889Z] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:327)

[2022-08-03T13:54:12.889Z] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:314)

[2022-08-03T13:54:12.889Z] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:307)

[2022-08-03T13:54:12.889Z] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:293)

[2022-08-03T13:54:12.889Z] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:417)

[2022-08-03T13:54:12.889Z] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:339)

[2022-08-03T13:54:12.889Z] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)

[2022-08-03T13:54:12.889Z] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)

[2022-08-03T13:54:12.889Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)

[2022-08-03T13:54:12.889Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)

[2022-08-03T13:54:12.889Z] 	at java.base/java.lang.Thread.run(Thread.java:833)

[2022-08-03T13:54:12.889Z] Caused by: org.gradle.api.internal.tasks.properties.PropertyEvaluationException: Error while evaluating property 'jvmArgumentProviders.koverArgumentsProvider$0.koverExtension.intellijEngineVersion' of task ':utils:common:test'

[2022-08-03T13:54:12.889Z] 	at org.gradle.api.internal.tasks.properties.InputParameterUtils.prepareInputParameterValue(InputParameterUtils.java:33)

[2022-08-03T13:54:12.889Z] 	at org.gradle.api.internal.tasks.execution.TaskExecution.lambda$visitRegularInputs$1(TaskExecution.java:309)

[2022-08-03T13:54:12.889Z] 	at org.gradle.internal.execution.fingerprint.impl.DefaultInputFingerprinter$InputCollectingVisitor.visitInputProperty(DefaultInputFingerprinter.java:106)

[2022-08-03T13:54:12.889Z] 	at org.gradle.api.internal.tasks.execution.TaskExecution.visitRegularInputs(TaskExecution.java:309)

[2022-08-03T13:54:12.889Z] 	at org.gradle.internal.execution.fingerprint.impl.DefaultInputFingerprinter.fingerprintInputProperties(DefaultInputFingerprinter.java:61)

[2022-08-03T13:54:12.889Z] 	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.captureExecutionStateWithOutputs(CaptureStateBeforeExecutionStep.java:193)

[2022-08-03T13:54:12.889Z] 	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.lambda$captureExecutionState$1(CaptureStateBeforeExecutionStep.java:141)

[2022-08-03T13:54:12.889Z] 	at org.gradle.internal.execution.steps.BuildOperationStep$1.call(BuildOperationStep.java:37)

[2022-08-03T13:54:12.889Z] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)

[2022-08-03T13:54:12.889Z] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.execution.steps.BuildOperationStep.operation(BuildOperationStep.java:34)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.captureExecutionState(CaptureStateBeforeExecutionStep.java:130)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.lambda$execute$0(CaptureStateBeforeExecutionStep.java:75)

[2022-08-03T13:54:12.890Z] 	at java.base/java.util.Optional.flatMap(Optional.java:289)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:75)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:50)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.executeWithNoEmptySources(SkipEmptyWorkStep.java:254)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.executeWithNoEmptySources(SkipEmptyWorkStep.java:209)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:88)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:56)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:32)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:21)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:43)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:31)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:40)

[2022-08-03T13:54:12.890Z] 	at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:281)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:40)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:27)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:44)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:33)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:76)

[2022-08-03T13:54:12.890Z] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:139)

[2022-08-03T13:54:12.890Z] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:128)

[2022-08-03T13:54:12.890Z] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)

[2022-08-03T13:54:12.890Z] 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)

[2022-08-03T13:54:12.890Z] 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)

[2022-08-03T13:54:12.890Z] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)

[2022-08-03T13:54:12.890Z] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)

[2022-08-03T13:54:12.890Z] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)

[2022-08-03T13:54:12.890Z] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)

[2022-08-03T13:54:12.890Z] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)

[2022-08-03T13:54:12.890Z] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)

[2022-08-03T13:54:12.890Z] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)

[2022-08-03T13:54:12.890Z] 	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:69)

[2022-08-03T13:54:12.890Z] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:327)

[2022-08-03T13:54:12.890Z] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:314)

[2022-08-03T13:54:12.890Z] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:307)

[2022-08-03T13:54:12.890Z] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:293)

[2022-08-03T13:54:12.890Z] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:417)

[2022-08-03T13:54:12.890Z] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:339)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)

[2022-08-03T13:54:12.890Z] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)

[2022-08-03T13:54:12.890Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)

[2022-08-03T13:54:12.890Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)

[2022-08-03T13:54:12.890Z] 	at java.base/java.lang.Thread.run(Thread.java:833)

[2022-08-03T13:54:12.890Z] Caused by: org.gradle.api.internal.provider.AbstractProperty$PropertyQueryException: Failed to calculate the value of extension 'kover' property 'intellijEngineVersion'.

[2022-08-03T13:54:12.890Z] 	at org.gradle.api.internal.provider.AbstractProperty.finalizeNow(AbstractProperty.java:239)

[2022-08-03T13:54:12.890Z] 	at org.gradle.api.internal.provider.AbstractProperty.beforeRead(AbstractProperty.java:230)

[2022-08-03T13:54:12.890Z] 	at org.gradle.api.internal.provider.AbstractProperty.calculateOwnValue(AbstractProperty.java:126)

[2022-08-03T13:54:12.890Z] 	at org.gradle.api.internal.provider.AbstractMinimalProvider.getOrNull(AbstractMinimalProvider.java:92)

[2022-08-03T13:54:12.890Z] 	at org.gradle.api.internal.provider.ProviderResolutionStrategy$1.resolve(ProviderResolutionStrategy.java:27)

[2022-08-03T13:54:12.890Z] 	at org.gradle.util.internal.DeferredUtil.unpack(DeferredUtil.java:59)

[2022-08-03T13:54:12.890Z] 	at org.gradle.util.internal.DeferredUtil.unpackOrNull(DeferredUtil.java:49)

[2022-08-03T13:54:12.890Z] 	at org.gradle.api.internal.tasks.properties.InputParameterUtils.prepareInputParameterValue(InputParameterUtils.java:39)

[2022-08-03T13:54:12.890Z] 	at org.gradle.api.internal.tasks.properties.InputParameterUtils.prepareInputParameterValue(InputParameterUtils.java:31)

[2022-08-03T13:54:12.890Z] 	... 71 more

[2022-08-03T13:54:12.890Z] Caused by: java.lang.UnsupportedOperationException: This property is in an unexpected state.

[2022-08-03T13:54:12.890Z] 	at org.gradle.api.internal.provider.AbstractProperty$FinalizedValue.unexpected(AbstractProperty.java:530)

[2022-08-03T13:54:12.890Z] 	at org.gradle.api.internal.provider.AbstractProperty$FinalizedValue.forUpstream(AbstractProperty.java:494)

[2022-08-03T13:54:12.890Z] 	at org.gradle.api.internal.provider.AbstractProperty.finalizeNow(AbstractProperty.java:236)

[2022-08-03T13:54:12.890Z] 	... 79 more

[2022-08-03T13:54:12.890Z] 
```

**Comment by NikolayMetchev** [comment]
I've just discovered that we had the following code:
```
intellijEngineVersion.set(libs.versions.intellijCoverageAgent.get())
```
So I am going to change to 
```
intellijEngineVersion.set(libs.versions.intellijCoverageAgent)
```

will report back if it doesn't fix the problem.

**Comment by shanshin** [comment]
Hi,
if it doesn't work, could you send an issue reproducer?

**Comment by shanshin** [comment]
Feel free to open new bug issue if the problem reproduced again.
