### ISSUE TITLE
0.6.0: Class org/locationtech/jts/geom/Geometry not found

### ISSUE THREAD

**Issue by hfhbd** [Kotlin/kotlinx-kover#232]
I upgrade from 0.5.0 to 0.6.0 and now koverVerify fails with this error message, but the task is successful.

build/kover/errors/jvmTest.log
```
[2022.09.02 09:49:17] (Coverage): Error during class instrumentation: org.h2.value.ValueToObjectConverter
java.lang.RuntimeException: java.io.IOException: Class org/locationtech/jts/geom/Geometry not found
	at com.intellij.rt.coverage.instrumentation.AbstractIntellijClassfileTransformer$MyClassWriter.getCommonSuperClass(AbstractIntellijClassfileTransformer.java:200)
	at org.jetbrains.coverage.org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1202)
	at org.jetbrains.coverage.org.objectweb.asm.Frame.merge(Frame.java:1299)
	at org.jetbrains.coverage.org.objectweb.asm.Frame.merge(Frame.java:1244)
	at org.jetbrains.coverage.org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
	at org.jetbrains.coverage.org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546)
	at org.jetbrains.coverage.org.objectweb.asm.MethodVisitor.visitMaxs(MethodVisitor.java:773)
	at org.jetbrains.coverage.org.objectweb.asm.commons.LocalVariablesSorter.visitMaxs(LocalVariablesSorter.java:148)
	at com.intellij.rt.coverage.instrumentation.LocalVariableInserter.visitMaxs(LocalVariableInserter.java:54)
	at org.jetbrains.coverage.org.objectweb.asm.MethodVisitor.visitMaxs(MethodVisitor.java:773)
	at org.jetbrains.coverage.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:769)
	at com.intellij.rt.coverage.instrumentation.LineEnumerator.visitEnd(LineEnumerator.java:68)
	at org.jetbrains.coverage.org.objectweb.asm.MethodVisitor.visitEnd(MethodVisitor.java:783)
	at org.jetbrains.coverage.org.objectweb.asm.MethodVisitor.visitEnd(MethodVisitor.java:783)
	at com.intellij.rt.coverage.instrumentation.filters.visiting.ClosingBracesFilter.visitEnd(ClosingBracesFilter.java:54)
	at org.jetbrains.coverage.org.objectweb.asm.MethodVisitor.visitEnd(MethodVisitor.java:783)
	at org.jetbrains.coverage.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1486)
	at org.jetbrains.coverage.org.objectweb.asm.ClassReader.accept(ClassReader.java:712)
	at org.jetbrains.coverage.org.objectweb.asm.ClassReader.accept(ClassReader.java:395)
	at com.intellij.rt.coverage.instrumentation.AbstractIntellijClassfileTransformer.instrument(AbstractIntellijClassfileTransformer.java:125)
	at com.intellij.rt.coverage.instrumentation.AbstractIntellijClassfileTransformer.transformInner(AbstractIntellijClassfileTransformer.java:101)
	at com.intellij.rt.coverage.instrumentation.AbstractIntellijClassfileTransformer.transform(AbstractIntellijClassfileTransformer.java:60)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.h2.jdbc.JdbcPreparedStatement.setObject(JdbcPreparedStatement.java:496)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.set(JdbcPreparedStatementImpl.kt:29)
	at org.jetbrains.exposed.sql.IColumnType$DefaultImpls.setParameter(ColumnType.kt:70)
	at org.jetbrains.exposed.sql.ColumnType.setParameter(ColumnType.kt:85)
	at org.jetbrains.exposed.sql.statements.api.PreparedStatementApi$DefaultImpls.fillParameters(PreparedStatementApi.kt:13)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.fillParameters(JdbcPreparedStatementImpl.kt:12)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:52)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:143)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:128)
	at org.jetbrains.exposed.sql.AbstractQuery.iterator(AbstractQuery.kt:61)
	at org.jetbrains.exposed.sql.IterableExKt$mapLazy$1.iterator(IterableEx.kt:129)
	at kotlin.collections.CollectionsKt___CollectionsKt.firstOrNull(_Collections.kt:269)
	at app.softwork.ratelimit.DatabaseStorageTest$DBStorage$getOrNull$2.invokeSuspend(DatabaseStorageTest.kt:46)
	at app.softwork.ratelimit.DatabaseStorageTest$DBStorage$getOrNull$2.invoke(DatabaseStorageTest.kt)
	at app.softwork.ratelimit.DatabaseStorageTest$DBStorage$getOrNull$2.invoke(DatabaseStorageTest.kt)
	at org.jetbrains.exposed.sql.transactions.experimental.SuspendedKt$suspendedTransactionAsyncInternal$1.invokeSuspend(Suspended.kt:127)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.test.TestDispatcher.processEvent$kotlinx_coroutines_test(TestDispatcher.kt:28)
	at kotlinx.coroutines.test.TestCoroutineScheduler.tryRunNextTaskUnless$kotlinx_coroutines_test(TestCoroutineScheduler.kt:100)
	at kotlinx.coroutines.test.TestCoroutineScheduler.advanceUntilIdleOr$kotlinx_coroutines_test(TestCoroutineScheduler.kt:120)
	at kotlinx.coroutines.test.TestCoroutineScheduler.advanceUntilIdle(TestCoroutineScheduler.kt:113)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTestCoroutine(TestBuilders.kt:237)
	at kotlinx.coroutines.test.TestBuildersKt.runTestCoroutine(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$1$1.invokeSuspend(TestBuilders.kt:167)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$1$1.invoke(TestBuilders.kt)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$1$1.invoke(TestBuilders.kt)
	at kotlinx.coroutines.test.TestBuildersJvmKt$createTestResult$1.invokeSuspend(TestBuildersJvm.kt:13)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersJvmKt.createTestResult(TestBuildersJvm.kt:12)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest(TestBuilders.kt:166)
	at kotlinx.coroutines.test.TestBuildersKt.runTest(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest(TestBuilders.kt:154)
	at kotlinx.coroutines.test.TestBuildersKt.runTest(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest$default(TestBuilders.kt:147)
	at kotlinx.coroutines.test.TestBuildersKt.runTest$default(Unknown Source)
	at app.softwork.ratelimit.DatabaseStorageTest.dbTest(DatabaseStorageTest.kt:131)
	at app.softwork.ratelimit.DatabaseStorageTest.dbTest$default(DatabaseStorageTest.kt:120)
	at app.softwork.ratelimit.DatabaseStorageTest.dbBasedRateLimit(DatabaseStorageTest.kt:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

```kotlin
plugins {
    kotlin("multiplatform") version "1.7.10"
    id("org.jetbrains.kotlinx.kover") version "0.6.0"
}

repositories {
    mavenCentral()
}

kotlin {
    jvm()

    iosX64()
    iosArm64()
    iosArm32()
    iosSimulatorArm64()

    watchosX86()
    watchosX64()
    watchosArm32()
    watchosArm64()
    watchosSimulatorArm64()

    tvosX64()
    tvosArm64()
    tvosSimulatorArm64()

    macosX64()
    macosArm64()
    linuxX64()
}

kover {
    verify {
        onCheck.set(true)
        rule {
            bound {
                minValue = 100 // the code coverage is lower, so the task should fail...
            }
        }
    }
}
```
Project: https://github.com/hfhbd/RateLimit/pull/163/commits/e449c913ac4881e219137620d86b4bde192b4644

```
IntelliJ IDEA 2022.2.2 Preview (Ultimate Edition)
Build #IU-222.4167.9, built on September 1, 2022
Licensed to Philip Wedemann
Subscription is active.
Runtime version: 17.0.4+7-b469.53 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.0
GC: G1 Young Generation, G1 Old Generation
Memory: 8096M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
    com.intellij.nativeDebug (222.4167.4)
    com.intellij.grazie.pro (0.3.107-221-222)
    org.jetbrains.kotlin (222-1.7.20-Beta-release-102-IJ3345.90)
    org.jetbrains.idea.grammar (2021.1.2)
    app.softwork.kobol (0.0.30)
    PsiViewer (222-SNAPSHOT)
    nl.rubensten.texifyidea (0.7.22)
    PlantUML integration (5.17.1)
    com.squareup.sqldelight (2.0.0-alpha03)

Kotlin: 222-1.7.20-Beta-release-102-IJ3345.90
```

**Comment by shanshin** [comment]
Hi,
as a workaround, try to exclude H2 classes from agent instrumentation
```
kover {
    filters {
        classes {
            excludes += listOf("org.h2.*")
        }
    }

  // ...
}
```

**Comment by hfhbd** [comment]
Hey, thanks this works. But why is it now required? :)

**Comment by shanshin** [comment]
It looks like this is a bug in the latest version of the instrumentation agent

**Comment by zuevmaxim** [comment]
To solve this issue, we have to calculate frames manually during bytecode transformation. Now we ask ASM library to compute frames, but it requires implementing `ClassWriter.getCommonSuperClass` method, but it is impossible in case of absent classfiles on disk or generated classes.

**Comment by shanshin** [comment]
Duplicates of #418
