### ISSUE TITLE
0.6.0: coroutines build hang in EngineManager.findJarFile(EngineManager.kt:68)

### ISSUE THREAD

**Issue by PavelPunegov** [Kotlin/kotlinx-kover#233]
Building master branch of coroutines with Kover 0.6.0 leads to build hang. I'm running the next command
```
./gradlew --parallel -Dorg.gradle.daemon=false --no-build-cache clean :kotlinx-coroutines-core:compileTestKotlinLinux64 --debug
```
Build hangs on:
```
<====---------> 32% EXECUTING [1m 30s]
> Resolve dependencies of :kotlinx-coroutines-test:KoverEngineConfig
```

One thread in Gradle daemon JVM process contains the following
```
	at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:173)
	at org.gradle.api.internal.file.AbstractFileCollection.getSingleFile(AbstractFileCollection.java:160)
	at kotlinx.kover.engines.commons.EngineManager.findJarFile(EngineManager.kt:68)
	at kotlinx.kover.appliers.KoverProjectApplierKt.engineByVariant(KoverProjectApplier.kt:182)
	at kotlinx.kover.appliers.KoverProjectApplierKt$engineProvider$1.call(KoverProjectApplier.kt:174)
	at kotlinx.kover.appliers.KoverProjectApplierKt$engineProvider$1.call(KoverProjectApplier.kt)
	at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:72)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.getOrNull(AbstractMinimalProvider.java:93)
```

In the Gradle debug output there are messages that show that it downloaded :
```
2022-09-05T19:21:35.195+0200 [DEBUG] [org.gradle.internal.resource.transport.http.HttpResponseResource] Attempting to download resource https://repo.maven.apache.org/maven2/org/jetbrains/intellij/deps/coverage-report/1.0.17/coverage-report-1.0.17.pom.
2022-09-05T19:21:35.195+0200 [INFO] [org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor] Downloading https://repo.maven.apache.org/maven2/org/jetbrains/intellij/deps/coverage-report/1.0.17/coverage-report-1.0.17.pom to /Users/ppunegov/.gradle/.tmp/gradle_download17838441047431129196bin
2022-09-05T19:21:35.196+0200 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection [id: 1][route: {s}->https://repo.maven.apache.org:443] can be kept alive indefinitely
2022-09-05T19:21:35.196+0200 [DEBUG] [org.apache.http.impl.conn.DefaultManagedHttpClientConnection] http-outgoing-1: set socket timeout to 0
2022-09-05T19:21:35.196+0200 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection released: [id: 1][route: {s}->https://repo.maven.apache.org:443][total available: 1; route allocated: 1 of 20; total allocated: 1 of 20]
2022-09-05T19:21:35.197+0200 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Completing Build operation 'Download https://repo.maven.apache.org/maven2/org/jetbrains/intellij/deps/coverage-report/1.0.17/coverage-report-1.0.17.pom'
2022-09-05T19:21:35.197+0200 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Download https://repo.maven.apache.org/maven2/org/jetbrains/intellij/deps/coverage-report/1.0.17/coverage-report-1.0.17.pom' completed
2022-09-05T19:21:35.205+0200 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver] Metadata file found for module 'org.jetbrains.intellij.deps:coverage-report:1.0.17' in repository 'MavenRepo'.
2022-09-05T19:21:35.205+0200 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.modulecache.PersistentModuleMetadataCache] Recording module descriptor in cache: org.jetbrains.intellij.deps:coverage-report:1.0.17 [changing = false]
2022-09-05T19:21:35.206+0200 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver] Using org.jetbrains.intellij.deps:coverage-report:1.0.17 from Maven repository 'MavenRepo'

```

**Comment by PavelPunegov** [comment]
To reproduce the issue one needs to cherry-pick https://github.com/Kotlin/kotlinx.coroutines/pull/3386
Also for the stable reproducibility first remove `.m2` directory to trigger download the artifacts

**Comment by PavelPunegov** [comment]
Ran under the debugger. Provider is calculated in the task ':kotlinx-coroutines-test:jvmTest' that is visited from the task ':kotlinx-coroutines-test:cleanJvmTest'

Here is the whole stacktrace
```
"Execution worker for ':'" #609 prio=5 os_prio=31 cpu=64.30ms elapsed=88.63s tid=0x00007fe722aae000 nid=0x2080b waiting on condition  [0x0000700019bbb000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.8/Native Method)
	- parking to wait for  <0x000000076121b868> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.8/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@11.0.8/AbstractQueuedSynchronizer.java:2081)
	at org.gradle.internal.operations.DefaultBuildOperationQueue.lambda$waitForWorkToComplete$0(DefaultBuildOperationQueue.java:141)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$$Lambda$1218/0x0000000800fec840.run(Unknown Source)
	at org.gradle.internal.work.DefaultWorkerLeaseService.blocking(DefaultWorkerLeaseService.java:223)
	at org.gradle.internal.operations.DefaultBuildOperationQueue.waitForWorkToComplete(DefaultBuildOperationQueue.java:135)
	at org.gradle.internal.operations.DefaultBuildOperationQueue.waitForCompletion(DefaultBuildOperationQueue.java:106)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.executeInParallel(DefaultBuildOperationExecutor.java:143)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.runAll(DefaultBuildOperationExecutor.java:102)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.maybeDownloadMetadataInParallel(DependencyGraphBuilder.java:357)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.resolveEdges(DependencyGraphBuilder.java:262)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.traverseGraph(DependencyGraphBuilder.java:200)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.resolve(DependencyGraphBuilder.java:151)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver.resolve(DefaultArtifactDependencyResolver.java:141)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultConfigurationResolver.resolveGraph(DefaultConfigurationResolver.java:187)
	at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolveGraph(ShortCircuitEmptyConfigurationResolver.java:85)
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolveGraph(ErrorHandlingConfigurationResolver.java:76)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$1.call(DefaultConfiguration.java:655)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$1.call(DefaultConfiguration.java:646)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:646)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.lambda$resolveExclusively$4(DefaultConfiguration.java:626)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$$Lambda$534/0x0000000800697040.apply(Unknown Source)
	at org.gradle.api.internal.project.DefaultProjectStateRegistry$CalculatedModelValueImpl.update(DefaultProjectStateRegistry.java:464)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveExclusively(DefaultConfiguration.java:623)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:610)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1900(DefaultConfiguration.java:159)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$SelectedArtifactsProvider.getValue(DefaultConfiguration.java:1422)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$SelectedArtifactsProvider.getValue(DefaultConfiguration.java:1412)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getSelectedArtifacts(DefaultConfiguration.java:1486)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.visitContents(DefaultConfiguration.java:1473)
	at org.gradle.api.internal.file.AbstractFileCollection.getFiles(AbstractFileCollection.java:127)
	at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:173)
	at org.gradle.api.internal.file.AbstractFileCollection.getSingleFile(AbstractFileCollection.java:160)
	at kotlinx.kover.engines.commons.EngineManager.findJarFile(EngineManager.kt:68)
	at kotlinx.kover.appliers.KoverProjectApplierKt.engineByVariant(KoverProjectApplier.kt:182)
	at kotlinx.kover.appliers.KoverProjectApplierKt$engineProvider$1.call(KoverProjectApplier.kt:174)
	at kotlinx.kover.appliers.KoverProjectApplierKt$engineProvider$1.call(KoverProjectApplier.kt)
	at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:72)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.getOrNull(AbstractMinimalProvider.java:93)
	at org.gradle.api.internal.tasks.properties.annotations.NestedBeanAnnotationHandler.unpackProvider(NestedBeanAnnotationHandler.java:78)
	at org.gradle.api.internal.tasks.properties.annotations.NestedBeanAnnotationHandler.visitPropertyValue(NestedBeanAnnotationHandler.java:62)
	at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode.visitProperties(AbstractNestedRuntimeBeanNode.java:56)
	at org.gradle.api.internal.tasks.properties.bean.NestedRuntimeBeanNode.visitNode(NestedRuntimeBeanNode.java:41)
	at org.gradle.api.internal.tasks.properties.DefaultPropertyWalker.visitProperties(DefaultPropertyWalker.java:41)
	at org.gradle.api.internal.tasks.TaskPropertyUtils.visitProperties(TaskPropertyUtils.java:42)
	at org.gradle.api.internal.tasks.TaskPropertyUtils.visitProperties(TaskPropertyUtils.java:32)
	at org.gradle.api.internal.tasks.DefaultTaskOutputs.getFileProperties(DefaultTaskOutputs.java:144)
	at org.gradle.api.internal.tasks.DefaultTaskOutputs$TaskOutputUnionFileCollection.visitChildren(DefaultTaskOutputs.java:235)
	at org.gradle.api.internal.file.CompositeFileCollection.visitContents(CompositeFileCollection.java:119)
	at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:351)
	at org.gradle.api.internal.file.CompositeFileCollection.lambda$visitContents$0(CompositeFileCollection.java:119)
	at org.gradle.api.internal.file.CompositeFileCollection$$Lambda$543/0x0000000800695440.accept(Unknown Source)
	at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:64)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection$UnresolvedItemsCollector.visitContents(DefaultConfigurableFileCollection.java:372)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.visitChildren(DefaultConfigurableFileCollection.java:284)
	at org.gradle.api.internal.file.CompositeFileCollection.visitContents(CompositeFileCollection.java:119)
	at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:351)
	at org.gradle.api.internal.file.CompositeFileCollection.lambda$visitContents$0(CompositeFileCollection.java:119)
	at org.gradle.api.internal.file.CompositeFileCollection$$Lambda$543/0x0000000800695440.accept(Unknown Source)
	at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:64)
	at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:89)
	at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:97)
	at org.gradle.api.internal.file.DefaultFileCollectionFactory$ResolvingFileCollection.visitChildren(DefaultFileCollectionFactory.java:333)
	at org.gradle.api.internal.file.CompositeFileCollection.visitContents(CompositeFileCollection.java:119)
	at org.gradle.api.internal.file.AbstractFileCollection.getFiles(AbstractFileCollection.java:127)
	at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:173)
	at java.lang.Iterable.forEach(java.base@11.0.8/Iterable.java:74)
	at org.gradle.execution.plan.LocalTaskNode.addDestroyablesToMutations(LocalTaskNode.java:218)
	at org.gradle.execution.plan.LocalTaskNode.resolveMutations(LocalTaskNode.java:235)
	at org.gradle.execution.plan.DefaultExecutionPlan.getResolvedMutationInfo(DefaultExecutionPlan.java:739)
	at org.gradle.execution.plan.DefaultExecutionPlan.selectNext(DefaultExecutionPlan.java:651)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$executeNextNode$2(DefaultPlanExecutor.java:197)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$$Lambda$1479/0x00000008011a9840.transform(Unknown Source)
	at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:45)
	- locked <0x000000074095d700> (a java.lang.Object)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:186)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:140)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.8/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.8/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.8/Thread.java:834)

```

**Comment by tjerkw** [comment]
Not sure if related, but "clean" was also hanging for us: 

> Resolve dependencies of :ecomServer:KoverEngineConfig > Resolve dependencies of :ecomServer:runtimeClasspath > Resolve files of :server:runtimeClasspath

**Comment by shanshin** [comment]
@tjerkw, which version of Gradle are you using?

**Comment by tjerkw** [comment]
```
./gradlew --version

------------------------------------------------------------
Gradle 7.3.3
------------------------------------------------------------

Build time:   2021-12-22 12:37:54 UTC
Revision:     6f556c80f945dc54b50e0be633da6c62dbe8dc71

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.12 (JetBrains s.r.o. 11.0.12+0-b1504.28-7817840)
OS:           Mac OS X 12.2 aarch64
```

**Comment by shanshin** [comment]
@tjerkw, using a different version of Gradle (`7.5` or `7.5.1`) doesn't solve your problem?
