### ISSUE TITLE
Kover 0.6.1: No instrumentation registered! Must run under a registering instrumentation.

### ISSUE THREAD

**Issue by soywiz** [Kotlin/kotlinx-kover#248]
After running `./gradlew koverHtmlReport` in a kotlin multiplatform project configuring JVM, android and K/N targets I get this exception:

https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872

```
Caused by:
java.lang.IllegalStateException: No instrumentation registered! Must run under a registering instrumentation.
   at androidx.test.platform.app.InstrumentationRegistry.getInstrumentation(InstrumentationRegistry.java:45)
   at androidx.test.core.app.ApplicationProvider.getApplicationContext(ApplicationProvider.java:41)
```

I suspect it is due to the android target. Is it possible to disable some targets just for the kover build? Is there any way to prevent that exception from happening?

**Comment by soywiz** [comment]
Looking at the task it says `testDebugUnitTest` so I guess in the local machine as an Android unit test.
The thing is that im not running those Android unit tests under any circumstances. Im running connected tests in another CI job since I need the Application Context in some cases.
So I would like to prevent kover from using the Android unittests while still allowing to use connected tests when calling the original task directly

```
> Task :korau:testDebugUnitTest
[667](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:668)

[668](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:669)
com.soywiz.korau.format.AudioFormatTest > wavCorrupted FAILED
[669](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:670)
    java.lang.reflect.InvocationTargetException
[670](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:671)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[671](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:672)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[672](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:673)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[673](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:674)
        at java.lang.reflect.Method.invoke(Method.java:498)
[674](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:675)
        at com.soywiz.korio.async.AsyncExtAndroidKt$asyncTestEntryPoint$1.invokeSuspend(AsyncExtAndroid.kt:17)
[675](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:676)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[676](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:677)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[677](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:678)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
[678](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:679)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
[679](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:680)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
[680](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:681)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
[681](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:682)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
[682](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:683)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
[683](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:684)
        at com.soywiz.korio.async.AsyncExtAndroidKt.asyncTestEntryPoint(AsyncExtAndroid.kt:15)
[684](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:685)
        at com.soywiz.korio.async.AsyncExtKt.suspendTest-PRSvZHU(AsyncExt.kt:71)
[685](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:686)
        at com.soywiz.korio.async.AsyncExtKt.suspendTest-ljwR17E(AsyncExt.kt:74)
[686](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:687)
        at com.soywiz.korio.async.AsyncExtKt.suspendTest-ljwR17E$default(AsyncExt.kt:74)
[687](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:688)
        at com.soywiz.korau.format.AudioFormatTest.wavCorrupted(AudioFormatTest.kt:25)
[688](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:689)

[689](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:690)
        Caused by:
[690](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:691)
        java.lang.IllegalStateException: No instrumentation registered! Must run under a registering instrumentation.
[691](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:692)
            at androidx.test.platform.app.InstrumentationRegistry.getInstrumentation(InstrumentationRegistry.java:45)
[692](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:693)
            at androidx.test.core.app.ApplicationProvider.getApplicationContext(ApplicationProvider.java:41)
[693](https://github.com/korlibs/korge/actions/runs/3180418274/jobs/5184004872#step:8:694)
            ... 18 more
 ```

**Comment by soywiz** [comment]
Sorry, I searched for the exception I got and didn't find anything, but now I see there is a section in the README:
It is explained here in the case someone looks for this specific exception and how to avoid it:

https://github.com/Kotlin/kotlinx-kover#configuring-jvm-test-task

Closing the issue
