### ISSUE TITLE
Errors for both IntelliJ and Jacoco coverage in android studio

### ISSUE THREAD

**Issue by jd-elt** [Kotlin/kotlinx-kover#309]
**Describe the bug**
Enabling kover for an android project on 0.7.0-alpha (and previous) I get errors when running with coverage in intellij. It works fine generating HTML and XML reports

**Errors**
No errors in "errors" directory.

When I try and run with IntelliJ coverage I get this error repeatedly and `useKoverTool`:

```
Could not stop org.gradle.internal.actor.internal.DefaultActorFactory$NonBlockingActor@49f9dd8.
org.gradle.internal.dispatch.DispatchException: Could not dispatch message [MethodInvocation method: processTestClass(DefaultTestClassRunInfo(com.elt.passsystem.ui.screens.task.IsReadyToSubmitUseCaseTest))].
	at org.gradle.internal.dispatch.ExceptionTrackingFailureHandler.dispatchFailed(ExceptionTrackingFailureHandler.java:35)
	at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:32)
	at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:87)
	at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:36)
	at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:71)
	at org.gradle.internal.concurrent.InterruptibleRunnable.run(InterruptibleRunnable.java:42)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 171' finished with non-zero exit value 1
	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:415)
	at org.gradle.process.internal.worker.DefaultWorkerProcess.onProcessStop(DefaultWorkerProcess.java:145)
	at org.gradle.process.internal.worker.DefaultWorkerProcess.access$000(DefaultWorkerProcess.java:42)
	at org.gradle.process.internal.worker.DefaultWorkerProcess$1.executionFinished(DefaultWorkerProcess.java:98)
```

When I change to coverage with Jacoco and `useJacocoTool`:

```aused by: java.lang.LinkageError: loader 'bootstrap' attempted duplicate class definition for java.lang.$JaCoCo. (java.lang.$JaCoCo is in module java.base of loader 'bootstrap')
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.System$2.defineClass(System.java:2131)
	at java.base/java.lang.invoke.MethodHandles$Lookup.defineClass(MethodHandles.java:962)
	... 13 more
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jacoco.agent.rt.internal_3570298.core.runtime.InjectedClassRuntime$Lookup.defineClass(InjectedClassRuntime.java:134)
	at org.jacoco.agent.rt.internal_3570298.core.runtime.InjectedClassRuntime.startup(InjectedClassRuntime.java:54)
	at org.jacoco.agent.rt.internal_3570298.PreMain.premain(PreMain.java:53)
	... 6 more
Caused by: java.lang.LinkageError: loader 'bootstrap' attempted duplicate class definition for java.lang.$JaCoCo. (java.lang.$JaCoCo is in module java.base of loader 'bootstrap')
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.System$2.defineClass(System.java:2131)
	at java.base/java.lang.invoke.MethodHandles$Lookup.defineClass(MethodHandles.java:962)
	... 13 more
```

It runs when I do not do either of the "use" methods, but then coverage does not display correctly

**Expected behavior**
To connect to Android Studio and display coverage

**Reproducer**
Not sure exactly what is causing it, I cannot share the project

**Reports**
If applicable, report files or screenshots.

**Environment**
 - Kover Gradle Plugin version: 0.7.0-alpha
 - Gradle version: [e.g. 7.5.1] 7.5.1
 - Kotlin project type: [e.g. Kotlin/JVM, Kotlin/Multiplatform, Kotlin/Android] android
 - Coverage Engine version (if customized in build script): See above
 - Other context important for this bug: [e.g. OS version]

**Comment by shanshin** [comment]
Hi, 
at the moment, Kover is not supported in IDEA and Android Studio, so when running tests with coverage from IDE, it is recommended to disable Kover instrumentation.

e.g. you may configure Kover
```
kover {
    disabledForProject = hasProperty("disableKover")
}
```  
and pass -PdisableKover arguments into IDE args

Duplicates #267 and #7

**Comment by shanshin** [comment]
Closed as a duplicate

**Comment by trevjonez** [comment]
It is worth mentioning you will get the same bootstrap duplicate error if your android build config is also setting coverage to true.

```kotlin
val Project.androidCoverage: Boolean
    get() = project.hasProperty("androidCoverage") && checkNotNull(findProperty("androidCoverage")).toString().toBoolean()

android {
  buildTypes {
    debug {
      enableAndroidTestCoverage = androidCoverage
      enableUnitTestCoverage = false // managed by kover
    }
  }
}

kover {
  // Disable when android test instrumentation is enabled so it doesn't double instrument
  disabledForProject = androidCoverage
  // Sonarcloud only understands jacoco xml reports :(
  useJacocoTool() 
}
```

**Comment by shanshin** [comment]
>   // Sonarcloud only understands jacoco xml reports :(

@trevjonez, the Kover XML report should be as similar as possible to the JaCoCo report, what was the discrepancy?

**Comment by trevjonez** [comment]
> @trevjonez, the Kover XML report should be as similar as possible to the JaCoCo report, what was the discrepancy?

@shanshin It seems I made a bad assumption that the structure was different. Comparing the two now and it looks like it might work. I will test it and post back once I see what falls out. 

Only thing suspect as I look at this now is that the kover report is missing the line param on the method elements.
