### ISSUE TITLE
Kover does not recognizes any coverage produced by Gradle Test Kit

### ISSUE THREAD

**Issue by tomkoptel** [Kotlin/kotlinx-kover#453]
**How can I configure Kover, so that it includes code coverage data for the Gradle plugin tested with [Gradle Test Kit](https://docs.gradle.org/current/userguide/test_kit.html)?**

I have a project with the custom Gradle Plugin. I have tests written based on [Gradle Test Kit](https://docs.gradle.org/current/userguide/test_kit.html). I do apply the kover plugin following way.
```toml
[versions]
kover = { require = "0.7.3" }

[plugins]
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
```
I apply plugin first to the root of the project:
```
android/build.gradle.kts
build.gradle <-- here
settings.gradle
```
```groovy
plugins {
   alias(pluginLibs.plugins.kover) apply false
}
```
Then in my plugins source module:
```
mymodule/build.gradle.kts <-- here
build.gradle 
settings.gradle
```
```kotlin
plugins {
    `kotlin-dsl`
    id("java-gradle-plugin")
    id("groovy-gradle-plugin")
    id("org.jetbrains.kotlinx.kover")
}
```
Running `./gradlew :mymodule:tasks` produces list of tasks
```
Verification tasks
------------------
koverBinaryReport - Task to generate binary coverage report in IntelliJ format for JVM project or Kotlin/MPP JVM targets. Android measurements for specific build variant can be merged
koverHtmlReport - Task to generate HTML coverage report for JVM project or Kotlin/MPP JVM targets. Android measurements for specific build variant can be merged
koverLog - Task to print coverage to log for JVM project or Kotlin/MPP JVM targets. Android measurements for specific build variant can be merged
koverVerify - Task to validate coverage bounding rules for JVM project or Kotlin/MPP JVM targets. Android measurements for specific build variant can be merged
koverXmlReport - Task to generate XML coverage report for JVM project or Kotlin/MPP JVM targets. Android measurements for 
```

Running `koverLog` produces low coverage number. `koverHtmlReport` shows that the plugins code is not executed.
<img width="539" alt="Screenshot 2023-08-17 at 14 58 47" src="https://github.com/Kotlin/kotlinx-kover/assets/758909/0dbbab99-3b55-4cd4-9b41-37db8f9fe18b">

I found plugin dedicated to the `Jacoco`, so that its coverage file reported when the `GradleRunner` executes the build https://github.com/koral--/jacoco-gradle-testkit-plugin

**Comment by tomkoptel** [comment]
I found following plugin for Jacoco https://github.com/koral--/jacoco-gradle-testkit-plugin and the one points to https://discuss.gradle.org/t/gradle-plugins-integration-tests-code-coverage-with-jacoco-plugin/12403/7
I've configured the project to have both `kover` and `pl.droidsonroids.jacoco.testkit` at the same time. Then I've switched `kover` to jacoco.
```groovy
kover {
    useJacoco()
}
```

Executing `gw :android:koverHtmlReport` gives me an error (full stacktrace below):
```
Caused by: java.lang.LinkageError: loader 'bootstrap' attempted duplicate class definition for java.lang.$JaCoCo. (java.lang.$JaCoCo is in module java.base of loader 'bootstrap')
```

According to the docs of `pl.droidsonroids.jacoco.testkit` we are copying contents of generated `build/testkit/test/testkit-gradle.properties` to the `gradle.properties` file of the project under test. The contents of file is:
```
#Generated by pl.droidsonroids.jacoco.testkit
org.gradle.jvmargs="-javaagent\:/Users/myuser/.gradle/caches/modules-2/files-2.1/org.jacoco/org.jacoco.agent/0.8.9/ad836d1c585c7e1dbf5cf828efa34528d9700303/org.jacoco.agent-0.8.9-runtime.jar\=destfile\=/Users/myuser/myproject/build/jacoco/test.exec"
```

Stacktrace of having both `kover` and `pl.droidsonroids.jacoco.testkit` simultaneously.
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jacoco.agent.rt.internal_4481564.core.runtime.InjectedClassRuntime$Lookup.defineClass(InjectedClassRuntime.java:134)
        at org.jacoco.agent.rt.internal_4481564.core.runtime.InjectedClassRuntime.startup(InjectedClassRuntime.java:54)
        at org.jacoco.agent.rt.internal_4481564.PreMain.premain(PreMain.java:50)
        ... 6 more
Caused by: java.lang.LinkageError: loader 'bootstrap' attempted duplicate class definition for java.lang.$JaCoCo. (java.lang.$JaCoCo is in module java.base of loader 'bootstrap')
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.System$2.defineClass(System.java:2131)
        at java.base/java.lang.invoke.MethodHandles$Lookup.defineClass(MethodHandles.java:962)
        ... 13 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jacoco.agent.rt.internal_4481564.core.runtime.InjectedClassRuntime$Lookup.defineClass(InjectedClassRuntime.java:134)
        at org.jacoco.agent.rt.internal_4481564.core.runtime.InjectedClassRuntime.startup(InjectedClassRuntime.java:54)
        at org.jacoco.agent.rt.internal_4481564.PreMain.premain(PreMain.java:50)
        ... 6 more
Caused by: java.lang.LinkageError: loader 'bootstrap' attempted duplicate class definition for java.lang.$JaCoCo. (java.lang.$JaCoCo is in module java.base of loader 'bootstrap')
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.System$2.defineClass(System.java:2131)
        at java.base/java.lang.invoke.MethodHandles$Lookup.defineClass(MethodHandles.java:962)
        ... 13 more
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
Process 'Gradle Test Executor 13' finished with non-zero exit value 134
org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 13' finished with non-zero exit value 134
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:415)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.onProcessStop(DefaultWorkerProcess.java:145)
        at org.gradle.process.internal.worker.DefaultWorkerProcess.access$000(DefaultWorkerProcess.java:42)
        at org.gradle.process.internal.worker.DefaultWorkerProcess$1.executionFinished(DefaultWorkerProcess.java:98)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:43)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:257)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:164)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:148)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at com.sun.proxy.$Proxy139.executionFinished(Unknown Source)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:221)
        at org.gradle.process.internal.DefaultExecHandle.finished(DefaultExecHandle.java:355)
        at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunner.java:110)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:84)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by tomkoptel** [comment]
I found another discussion on the Gradle repo https://github.com/gradle/gradle/issues/1465.
It seems that the Gradle Test Kit does not support Jacoco or any other java agent out of box or allows to configure one.

**Comment by tomkoptel** [comment]
I was able to collect coverage reports by removing `kover` from the build configuration. Though it is not a solution I am looking for. I would like to have reports handled by `kover`.

For those interested in the working solution, but **without `kover`**. Add those to the project and follow the steps described on https://github.com/koral--/jacoco-gradle-testkit-plugin then execute `.gradlew :myproject:jacocoTestReport`
```kotlin
plugins {
    `kotlin-dsl`
    jacoco
    alias(pluginLibs.plugins.jacocoGradleTestKit)
}

tasks.test {
    // report is always generated after tests run
    finalizedBy(tasks.jacocoTestReport)
}

tasks.jacocoTestReport {
    // tests are required to run before generating the report
    dependsOn(tasks.test)
}
```
Somewhere under `src/main/kotlin/test`.
```kotlin
import java.io.File
import java.io.InputStream
import org.gradle.testkit.runner.GradleRunner

object GradleRunnerExt {
    fun GradleRunner.withJaCoCo(): GradleRunner {
        val testkitProps = javaClass.classLoader.getResourceAsStream("testkit-gradle.properties")!!
        testkitProps.toFile(File(projectDir, "gradle.properties"))
        return this
    }

    private fun InputStream.toFile(file: File) {
        use { input ->
            file.outputStream().use { input.copyTo(it) }
        }
    }
}
```
then in test
```kotlin
class AwesomeTest {

    fun InputStream.toFile(file: File) {
        use { input ->
            file.outputStream().use { input.copyTo(it) }
        }
    }

    fun GradleRunner.withJaCoCo(): GradleRunner {
        javaClass.classLoader.getResourceAsStream("testkit-gradle.properties").toFile(File(projectDir, "gradle.properties"))
        return this
    }

    @get:Rule
    val temporaryFolder = TemporaryProjectFolder()

    @Test
    fun `empty project builds successfuly`() {
        val result = GradleRunner.create()
                .withProjectDir(temporaryFolder.root)
                .withTestKitDir(temporaryFolder.newFolder())
                .withPluginClasspath()
                .withJaCoCo()
                .build()
    }
}
```

**Comment by DanySK** [comment]
nice work so far @tomkoptel! @shanshin: even if it's not supported out of the box, is there any way to instrument Gradle so that Kover can do its job?
For JaCoCo, it's matter of attaching a java agent, is it the same for kover (at least kover-jvm)?

**Comment by shanshin** [comment]
This task will be taken into account when [migrating to Kotlin Gradle Plugin](https://github.com/Kotlin/kotlinx-kover/issues/724).

In the future, it will be moved to the Kotlin task tracker, or closed if it loses relevance.
