### ISSUE TITLE
Kover Html Report Fail ( KMP )

### ISSUE THREAD

**Issue by droidmatic34** [Kotlin/kotlinx-kover#58]
> Task :koverHtmlReport FAILED
HTML generation failed.
java.io.FileNotFoundException: /IdeaProjects/kmp-circleci-client/build/kover/CircleCi/test.ic.smap (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at com.intellij.rt.coverage.instrumentation.SaveHook.loadSourceMapFromFile(SaveHook.java:136)
        at com.intellij.rt.coverage.instrumentation.SaveHook.loadAndApplySourceMap(SaveHook.java:121)
        at com.intellij.rt.coverage.report.Reporter.getProjectData(Reporter.java:72)
        at com.intellij.rt.coverage.report.Reporter.createHTMLReport(Reporter.java:103)
        at com.intellij.rt.coverage.report.Main.main(Main.java:47)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':koverHtmlReport'.
> Process 'command '/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

**Comment by shanshin** [comment]
Duplicate #46

**Comment by qwwdfsad** [comment]
Will be fixed in 0.4.2
