### ISSUE TITLE
java.lang.NullPointerException: Cannot load from int array because "__$localBranchHits$__" is null

### ISSUE THREAD

**Issue by CLOVIS-AI** [Kotlin/kotlinx-kover#61]
Adding Kover to my project breaks the tests.

# Reproduction

```bash
$ git clone https://gitlab.com/braindot/clovis.git  # see https://gitlab.com/braindot/clovis
$ cd clovis
$ git switch --detach e4a59cc6
$ ./gradlew test  # this should work (executes JVM tests from the different modules)
```

In the root `build.gradle.kts`, in the `plugins` block, add `id("org.jetbrains.kotlinx.kover") version "0.4.1"`.

Run `./gradlew test` again, it now fails.

# Stacktrace

All tests fail with stacktraces similar to this one:

```
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot load from int array because "__$localBranchHits$__" is null
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot load from int array because "__$localBranchHits$__" is null
        at com.datastax.oss.driver.shaded.guava.common.collect.IndexedImmutableSet$1.<init>(IndexedImmutableSet.java:57)
        at com.datastax.oss.driver.shaded.guava.common.collect.IndexedImmutableSet.createAsList(IndexedImmutableSet.java:57)
        at com.datastax.oss.driver.shaded.guava.common.collect.ImmutableSet.asList(ImmutableSet.java:310)
        at com.datastax.oss.driver.shaded.guava.common.collect.IndexedImmutableSet.iterator(IndexedImmutableSet.java:32)
        at com.datastax.oss.driver.shaded.guava.common.collect.IndexedImmutableSet.iterator(IndexedImmutableSet.java:26)
        at com.datastax.oss.driver.shaded.guava.common.collect.Sets$3$1.<init>(Sets.java:904)
        at com.datastax.oss.driver.shaded.guava.common.collect.Sets$3.iterator(Sets.java:903)
        at com.datastax.oss.driver.internal.core.metadata.schema.refresh.SchemaRefresh.compute(SchemaRefresh.java:52)
        at com.datastax.oss.driver.internal.core.metadata.MetadataManager.apply(MetadataManager.java:512)
        at com.datastax.oss.driver.internal.core.metadata.MetadataManager$SingleThreaded.parseAndApplySchemaRows(MetadataManager.java:490)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        ... 6 more
```

**Comment by qwwdfsad** [comment]
Thanks! This is a bug in the instrumentation agent (https://youtrack.jetbrains.com/issue/IDEA-282575).
We'll release a new version as soon as it gets fixed

**Comment by shanshin** [comment]
@CLOVIS-AI, is this bug reproduced in version `0.5.0-RC2`?
