### ISSUE TITLE
Kover task fails in GitHub Actions CI with java.io.FileNotFoundException

### ISSUE THREAD

**Issue by czyzby** [Kotlin/kotlinx-kover#74]
See [this run](https://github.com/libktx/ktx/runs/4290997615) for details. The report generation task was triggered by `./gradlew check`. The plugin had no custom configuration for the plugin other than the recommended import (`id("org.jetbrains.kotlinx.kover") version "0.4.2"`).

Here's the stack trace:

```
java.io.FileNotFoundException: /home/runner/work/ktx/ktx/script/build/kover/test.ic.smap (No such file or directory)
> Task :script:koverHtmlReport FAILED
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.intellij.rt.coverage.instrumentation.SaveHook.loadSourceMapFromFile(SaveHook.java:136)
	at com.intellij.rt.coverage.instrumentation.SaveHook.loadAndApplySourceMap(SaveHook.java:121)
	at com.intellij.rt.coverage.report.Reporter.getProjectData(Reporter.java:72)
	at com.intellij.rt.coverage.report.Reporter.createHTMLReport(Reporter.java:103)
	at com.intellij.rt.coverage.report.Main.main(Main.java:47)
XML generation failed.
```

**Comment by shanshin** [comment]
this may be due to a problem with caching the results of task execution, especially if `clean` was performed before or `check` was called twice.
Related #68

**Comment by czyzby** [comment]
Neither happened. The CI script uses the following Gradle calls:

```bash
./gradlew assemble install -x dokkaHtml -x dokkaZip
./gradlew check --continue
```

`install` or `assemble` do seem to trigger `:buildSrc:check`, but this is only the Gradle configuration itself - `check` is not called on any of the actual Kotlin modules.

**Comment by shanshin** [comment]
@czyzby, please check in version `0.4.3`.

**Comment by shanshin** [comment]
Feel free to reopen if the problem is not gone on `0.5.0`+
