### ISSUE TITLE
"Can't add different class with same name" in an Android project with the JACOCO engine

### ISSUE THREAD

**Issue by cristan** [Kotlin/kotlinx-kover#78]
**Steps to reproduce** (or use [the attached project](https://github.com/Kotlin/kotlinx-kover/files/7609152/TestKoverAndroidProject.zip))
* Create an empty Android Project in Android studio.
* Add the following after the buildscript block in the root build.gradle
```
plugins {
    id 'org.jetbrains.kotlinx.kover' version '0.4.2'
}
```

* Add the following in app/build.gradle:

```
kover {
    coverageEngine.set(kotlinx.kover.api.CoverageEngine.JACOCO)
}
```
* Change the repositoriesMode to RepositoriesMode.PREFER_SETTINGS (because [this change](https://github.com/Kotlin/kotlinx-kover/issues/34#issuecomment-963161529) isn't in 0.4.2 yet)

* Add this class

```
class Main {
    fun helloWorld() = "Hello ${world()}!"

    fun greet(s: String) = "Hello $s!"

    inline fun world() = "world"
}
```
* Change ExampleUnitTest:
```
class ExampleUnitTest {
    @Test
    fun testHello() {
        val m = Main()
        assert(m.greet(m.world()).contains("world"))
    }
}
```
* Clean the project
* Run the gradle tasks `koverVerify koverHtmlReport`

You then see this error:
```
Execution failed for task ':app:koverHtmlReport'.
> Error while creating report

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:koverHtmlReport'.
Caused by: : Error while creating report
...
Caused by: java.io.IOException: Error while analyzing /Users/cristan/AndroidStudioProjects/TestKoverAndroidProject/app/build/tmp/kotlin-classes/debug/com/example/testkoverandroidproject/Main.class.
	at org.jacoco.core.analysis.Analyzer.analyzerError(Analyzer.java:162)
	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:134)
	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:157)
	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:193)
	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:226)
	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:221)
	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:221)
	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:221)
	at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:221)
	at org.jacoco.ant.ReportTask.createBundle(ReportTask.java:570)
	at org.jacoco.ant.ReportTask.createReport(ReportTask.java:545)
	at org.jacoco.ant.ReportTask.execute(ReportTask.java:496)
	... 132 more
Caused by: java.lang.IllegalStateException: Can't add different class with same name: com/example/testkoverandroidproject/Main
	at org.jacoco.core.analysis.CoverageBuilder.visitCoverage(CoverageBuilder.java:106)
	at org.jacoco.core.analysis.Analyzer$1.visitEnd(Analyzer.java:99)
	at org.objectweb.asm.ClassVisitor.visitEnd(ClassVisitor.java:377)
	at org.jacoco.core.internal.flow.ClassProbesAdapter.visitEnd(ClassProbesAdapter.java:100)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:725)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:116)
	at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:132)
	... 142 more
```

**Comment by shanshin** [comment]
Related to #11

**Comment by esafirm** [comment]
I also got this error while using the Jacoco engine, could you elaborate on what's happening here since #11 is not really explaining anything. Thanks!

**Comment by shanshin** [comment]
@esafirm, if you are writing an Android project, you probably have classes with the same full qualified name in different flavors (or build types).
These classes fall into the classpath of the JaCoCo reporter and report generation fails due to ambiguity.

 API for limiting flavors is still in development (#18)

**Comment by ptsiogas** [comment]
I run into the same issue today. With Kover version 0.3.0 there was no issue though.
Are there any plans on fixing/work around this issue?

**Comment by shanshin** [comment]
@ptsiogas, the issue is serious and lies in an unsuitable API for Android.
It will be solved comprehensively and using a separate API for Android and updating reports to support flavours.

As a workaround, you can try to exclude a repeating class from instrumentation.

**Comment by shanshin** [comment]
Relates #18
