### ISSUE TITLE
Invalid escape characters in intellijreport.json

### ISSUE THREAD

**Issue by lars-reimann** [Kotlin/kotlinx-kover#82]
**Kover version:** 0.4.3
**Coverage Engine:** IntelliJ with default version
**OS:** Windows

-----------------------

Minimal `build.gradle.kts`:

```kt
plugins {
    id("org.jetbrains.kotlinx.kover") version "0.4.3"
}

repositories {
    mavenCentral()
}

kover {
    coverageEngine.set(kotlinx.kover.api.CoverageEngine.INTELLIJ)
    generateReportOnCheck.set(true)
}
```

When running `./gradlew check` on Windows I get the following output:
```
> Task :[REDACTED]:koverHtmlReport FAILED
com.intellij.rt.coverage.report.ReporterArgs$ArgParseException: Incorrect arguments in file [REDACTED]\build\tmp\koverHtmlReport\intellijreport.json
        at com.intellij.rt.coverage.report.ReporterArgs.from(ReporterArgs.java:66)
        at com.intellij.rt.coverage.report.Main.main(Main.java:29)
Caused by: org.json.JSONException: Illegal escape. at 17 [character 15 line 2]
        at org.json.JSONTokener.syntaxError(JSONTokener.java:507)
        at org.json.JSONTokener.nextString(JSONTokener.java:353)
        at org.json.JSONTokener.nextValue(JSONTokener.java:428)
        at org.json.JSONObject.<init>(JSONObject.java:252)
        at org.json.JSONObject.<init>(JSONObject.java:406)
        at com.intellij.rt.coverage.report.ReporterArgs.parse(ReporterArgs.java:72)
        at com.intellij.rt.coverage.report.ReporterArgs.from(ReporterArgs.java:62)
        ... 1 more
[REDACTED]\build\tmp\koverHtmlReport\intellijreport.json

Arguments must be passed in the following JSON format:
{
  "modules": [
    { "reports": [
        {"ic": "path to ic binary file", "smap": "path to source map file"}
      ] [OPTIONAL, absence means that all classes were not covered],
      "output": ["outputRoot1", "outputRoot2"],
      "sources": ["sourceRoot1", "sourceRoot2"]
    }
  ],
  "xml": "path to xml file" [OPTIONAL],
  "html": "path to html directory" [OPTIONAL]
}

FAILURE: Build failed with an exception.
```

This is the content of `intellijreport.json`:
```
{
  "html": "[REDACTED]\build\reports\kover\html",
  "modules": [
    { "reports": [ 
        
      ], 
      "output": [
        
      ],
      "sources": [
        
      ]
    }
  ]
}
```

I guess the `\` in the `html` property should be replaced by `\\`.

Jacoco works with 0.4.3, though, which is already workable.

**Comment by shanshin** [comment]
@lars-reimann, please check in `0.4.4`

**Comment by lars-reimann** [comment]
0.4.4 works, thank you very much.
